/**
 * Type-safe environment variable access.
 * App code should use `env.VAR_NAME` not `process.env.VAR_NAME`.
 */

const raw = {
  BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
  BETTER_AUTH_URL: process.env.BETTER_AUTH_URL,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  EMAIL_DOMAIN: process.env.EMAIL_DOMAIN,
  POLAR_ACCESS_TOKEN: process.env.POLAR_ACCESS_TOKEN,
  POLAR_WEBHOOK_SECRET: process.env.POLAR_WEBHOOK_SECRET,
  NEXT_PUBLIC_POLAR_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_POLAR_PUBLISHABLE_KEY,
  TRIGGER_SECRET_KEY: process.env.TRIGGER_SECRET_KEY,
  DATABASE_URL: process.env.DATABASE_URL ?? "file:local.db",
  FLY_API_TOKEN: process.env.FLY_API_TOKEN,
  FLY_ORG: process.env.FLY_ORG ?? "personal",
  POLAR_PRICE_STARTER_MONTHLY: process.env.POLAR_PRICE_STARTER_MONTHLY,
  POLAR_PRICE_STARTER_ANNUAL: process.env.POLAR_PRICE_STARTER_ANNUAL,
  POLAR_PRICE_PRO_MONTHLY: process.env.POLAR_PRICE_PRO_MONTHLY,
  POLAR_PRICE_PRO_ANNUAL: process.env.POLAR_PRICE_PRO_ANNUAL,
  POLAR_PRICE_TEAM_MONTHLY: process.env.POLAR_PRICE_TEAM_MONTHLY,
  POLAR_PRICE_TEAM_ANNUAL: process.env.POLAR_PRICE_TEAM_ANNUAL,
} as const;

export const env = {
  BETTER_AUTH_SECRET: raw.BETTER_AUTH_SECRET ?? "",
  BETTER_AUTH_URL: raw.BETTER_AUTH_URL ?? "http://localhost:3000",
  RESEND_API_KEY: raw.RESEND_API_KEY ?? "",
  EMAIL_DOMAIN: raw.EMAIL_DOMAIN ?? "kiln.build",
  POLAR_ACCESS_TOKEN: raw.POLAR_ACCESS_TOKEN ?? "",
  POLAR_WEBHOOK_SECRET: raw.POLAR_WEBHOOK_SECRET ?? "",
  NEXT_PUBLIC_POLAR_PUBLISHABLE_KEY: raw.NEXT_PUBLIC_POLAR_PUBLISHABLE_KEY ?? "",
  TRIGGER_SECRET_KEY: raw.TRIGGER_SECRET_KEY ?? "",
  DATABASE_URL: raw.DATABASE_URL,
  FLY_API_TOKEN: raw.FLY_API_TOKEN ?? "",
  FLY_ORG: raw.FLY_ORG,
  POLAR_PRICE_STARTER_MONTHLY: raw.POLAR_PRICE_STARTER_MONTHLY,
  POLAR_PRICE_STARTER_ANNUAL: raw.POLAR_PRICE_STARTER_ANNUAL,
  POLAR_PRICE_PRO_MONTHLY: raw.POLAR_PRICE_PRO_MONTHLY,
  POLAR_PRICE_PRO_ANNUAL: raw.POLAR_PRICE_PRO_ANNUAL,
  POLAR_PRICE_TEAM_MONTHLY: raw.POLAR_PRICE_TEAM_MONTHLY,
  POLAR_PRICE_TEAM_ANNUAL: raw.POLAR_PRICE_TEAM_ANNUAL,
};

export const OPS_TEAM_EMAILS: string[] = [];
