app = "kiln"
primary_region = "iad"

[build]
[build.args]
NEXT_PUBLIC_APP_URL = "https://kiln.fly.dev"

[http_service]
internal_port = 3000
force_https = true
auto_stop = true
auto_start = true

[http_service.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[checks]
[checks.status]
port = 3000
type = "http"
path = "/"

[vm]
size = "shared-cpu-2x"
memory = "4gb"

[mounts]
source = "kiln_data"
destination = "/data"
